name: Markdown Lint

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
          fix: true

      - name: Commit changes
        if: failure()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Fix markdown lint issues"
          git push
